telephone: 555.555.5555
seo:
  tagline: >-
    The Gathering Place is an event space that strives to serve everyone,
    regardless of circumstance. <br/> Work with us to have a beautiful
    experience.
location:
  city: Billings
  country: USA
  state: Montana
  street_address: 1234 Placey Place
