telephone: "5555555555"
telephone_display: "555-555-5555"

seo:
  tagline: > 
    The Gathering Place is an event space that strives to serve everyone, regardless of circumstance. <br/>
    Work with us to have a beautiful experience.

location:
  street_address: "1234 Place Place"
  city: "Billings"
  state: "Montana"
  country: "USA" 